Use Vue router to authenticate
gotechnica/platform-2020 pull request #122
Opened 2020-09-04 06:07 UTC by Ludikrous

Fixes a vulnerability where a user could see platform pages without logging in through a magic link.

Bug was caused because authentication was done in `mounted()`, which doesn't necessarily run when a new page is visited.
Now, auth is handled by the Vue router, which will check the cookies for auth every time the user visits a new page (i.e. the path is changed).

2020-09-04 18:56 UTC, burbelohugo requested changes

2020-09-04 18:56 UTC, burbelohugo commented on frontend/src/router/index.js
> +  if ((!Vue.cookie.get('userId')) && ((to.name !== 'Login' && to.name !== 'authenticate'))) {
Right now I cannot complete the authentication link flow (clicking a link sent in my email with the auth token and logging in) on this branch. I did some digging and it looks like we need to fix 2 things with this PR for it to work:
- Update line 236 to: `to.name !== 'Authenticate'` (note the uppercase A)
- Add `name: 'Authenticate',` where the authentication route is defined:
![Screen Shot 2020-09-04 at 2 56 13 PM](https://user-images.githubusercontent.com/30019505/92276345-cf757600-eebe-11ea-8e79-f39844461009.png)

2020-09-04 20:42 UTC, Ludikrous commented
@burbelohugo now that auth is done in the router, can we remove the check in `frontend/src/App.vue:34` (and also line 43)?

This should be safe because the check in the router runs more often, and also before the `mounted()` check.

2020-09-05 15:54 UTC, burbelohugo commented
@Ludikrous yes, please do so. I think that should be fine, the strategy you've implemented is a lot better than my quick fix 🎉

2020-09-06 18:54 UTC, burbelohugo approved these changes

2020-09-06 18:54 UTC, merged